Sudoku/Controllers/ChaptersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Antlr.Runtime.Misc;
using Newtonsoft.Json.Linq;
using Sudoku.DAL;
using Sudoku.Dtos.Incoming;
using Sudoku.Dtos.Outgoing;
using Sudoku.Models;
using Sudoku.Services;

namespace Sudoku.Controllers
{
    public class ChaptersController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private SudokuService sudokuService = new SudokuService();
        private UserService userService = new UserService();
        private int ChapterQuantity {  get; set; }
        public ChaptersController()
        {
        }

        // GET: Chapters
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> Chapters(int page, string chapterName = null)
        {

            var chapterPerPage = 5;
            int skipChapter = (page - 1) * chapterPerPage;
            
            List<ChapterDto> chapters;

            var userId = userService.GetUserId(Request);

            if (chapterName == "")
            {
                ChapterQuantity = await db.Chapters.CountAsync();

                chapters = await db.Chapters.OrderBy(x => x.CreateDate)
                                      .Skip(skipChapter).Take(chapterPerPage)
                                      .Include(x => x.TypeNavigation)
                                      .Select(x => new ChapterDto
                                      {
                                          Id = x.Id,
                                          Name = x.Name,
                                          Chap_file_path = x.Chap_file_path,
                                          CreateDate = x.CreateDate,
                                          Type_id = x.Type_id,
                                          TypeNavigation = x.TypeNavigation,
                                          IsCompleted = db.Submissions.Any(s => s.ChapterId == x.Id && s.UserId == userId && s.State == utility.StateCompleted)
                                      })
                                      .ToListAsync();
            }
            else
            {
                ChapterQuantity = await db.Chapters.Where(x => x.Name.Contains(chapterName)).CountAsync();

                chapters = await db.Chapters.Where(x => x.Name.Contains(chapterName))
                                      .OrderBy(x => x.CreateDate)
                                      .Skip(skipChapter).Take(chapterPerPage)
                                      .Include(x => x.TypeNavigation)
                                      .Select(x => new ChapterDto
                                      {
                                          Id = x.Id,
                                          Name = x.Name,
                                          Chap_file_path = x.Chap_file_path,
                                          CreateDate = x.CreateDate,
                                          Type_id = x.Type_id,
                                          TypeNavigation = x.TypeNavigation,
                                          IsCompleted = db.Submissions.Any(s => s.ChapterId == x.Id && s.UserId == userId && s.State == utility.StateCompleted)
                                      })
                                      .ToListAsync();
            }

            if (ChapterQuantity == 0)
                ViewBag.PageQuantity = 0;
            else if (ChapterQuantity < chapterPerPage)
                ViewBag.PageQuantity = 1;
            else
                ViewBag.PageQuantity = Math.Ceiling((double)ChapterQuantity / chapterPerPage);

            return View(chapters);
        }
        // GET: Chapters/Create
        public async Task<ActionResult> Upsert(string id)
        {
            var chapterCreateDto = new ChapterUpsertDto();
            var items = await db.ChapterTypes.OrderByDescending(x => x.Point).Select(selector => new SelectListItem
            {
                Text = selector.Name,
                Value = selector.Id,

            }).ToListAsync();


            chapterCreateDto.ChapterType = items;
            if(id != null)
            {
                var chapter = await db.Chapters.SingleOrDefaultAsync(x => x.Id == id);
                ViewBag.SudokuArr = sudokuService.ReadSudokuStringFromFile(chapter.Chap_file_path);
                chapterCreateDto.ChapterId = chapter.Id;
                chapterCreateDto.Name = chapter.Name;
                chapterCreateDto.Type_id = chapter.Type_id;
                chapterCreateDto.Chap_file_name = chapter.Chap_file_path;
            }

            else
            {
                char[,] sudokuArr = new char[9, 9];
                for (int i = 0; i < 9; i++)
                {
                    for (int j = 0; j < 9; j++)
                    {
                        sudokuArr[i, j] = '0';
                    }
                }
                chapterCreateDto.ChapterId = "";
                ViewBag.SudokuArr = sudokuService.FormatArrayToString(sudokuArr);
            }
            string userId = userService.GetUserId(Request);
            chapterCreateDto.RemainPost = await db.AuthorService.Where(x => x.UserId == userId).Select(x => x.RemainPostNumber).SingleOrDefaultAsync(); 

            ViewBag.DefaultSudoku = sudokuService.ReadSudokuStringFromFile("default-chapter.txt");
            return View(chapterCreateDto);
        }
        [HttpPost]
        public async Task<ActionResult> Upsert(ChapterUpsertDto chapterDto)
        {
            if (ModelState.IsValid)
            {

                var userId = userService.GetUserId(Request);
                var authorService = await db.AuthorService.Where(x => x.UserId == userId).SingleOrDefaultAsync();
                if(authorService.RemainPostNumber == 0)
                {
                    return Json(new { code = 409, msg = "You have run out of posts for today" });
                }
                authorService.RemainPostNumber--;

                if(chapterDto.ChapterId == null)
                {
                    var fileName = Guid.NewGuid().ToString() + ".txt";
                    await sudokuService.WriteSudokuStringToFile(fileName, chapterDto.SudokuString);

                    var chapter = new Chapter()
                    {
                        Name = chapterDto.Name,
                        Chap_file_path = fileName,
                        Type_id = chapterDto.Type_id,
                        CreateDate = DateTime.Now,
                        AuthorId = userId
                    };
                    db.Chapters.Add(chapter);
                }
                else
                {
                    await sudokuService.WriteSudokuStringToFile(chapterDto.Chap_file_name, chapterDto.SudokuString);
                    var chapter = await db.Chapters.FindAsync(chapterDto.ChapterId);
                    chapter.Type_id = chapterDto.Type_id;
                    chapter.Name = chapterDto.Name;
                }
                await db.SaveChangesAsync();
                return Json(new { code = 200 });
            }

            chapterDto.ChapterType = await db.ChapterTypes.OrderByDescending(x => x.Point).Select(selector => new SelectListItem
            {
                Text = selector.Name,
                Value = selector.Id,
            }).ToListAsync();
            return Json(new {code = 409, msg="Lack of information"});
        }

        [HttpPost]
        public ActionResult TestConflict(string sudokuString, int rows, int columns)
        {

            var sudokuArr = sudokuService.FormatStringToArr(sudokuString, rows, columns);
            return Json(sudokuService.TestSudoku(sudokuArr)); // return code 200 if success else return box that cause conflict
        }
        [HttpGet]
        public async Task<ActionResult> GenerateRiddle(int rows)
        {
            var annealing = new SimulatedAnnealing();
            var riddle = await annealing.getRandomRiddle(rows);
            var sudokuStr = sudokuService.FormatArrayToString(riddle);
            return Json(new { code = 200, sudokuString = sudokuStr }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Play(string id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> GetChapter(string chapterId)
        {
            Chapter chapter = await db.Chapters.Where(x => x.Id == chapterId).Include(nameof(Chapter.TypeNavigation)).FirstOrDefaultAsync();

            ChapterPlayDto chapterPlayDto = new ChapterPlayDto()
            {
                chapter = chapter,
                sudokuArr = sudokuService.ReadSudokuStringFromFile(chapter.Chap_file_path)
            };
            return View(chapterPlayDto);
        }
        [HttpPost]
        public async Task<ActionResult> Play(SubmitDto submitDto)
        {
            var type = submitDto.Type_Name;
            char[,] sudokuArr;

            var userId = userService.GetUserId(Request);

            if (type == "Easy")
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 5, 5);
            else if (type == "Medium")
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 7, 7);
            else
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 9, 9);

            string submitFileName = Guid.NewGuid().ToString().Substring(0, 6);
            string submitPath = Path.Combine(AppContext.BaseDirectory, "wwwroot", "Submission", submitFileName);

Sudoku/Views/Shared/Personal_section.cshtml
<style>
    .personal-section {
        position: absolute;
        right: 0;
        color: black;
        border: 1px ridge antiquewhite;
        background: whitesmoke;
        margin-top: 12px;
        border-radius: 6px;
        list-style: none;
        width: 230px;
        padding: 10px;
    }

    .w-15 {
        width: 15%;
    }

    .personal-section li {
        border-radius: 5px;
        text-align: start;
    }

        .personal-section li:hover {
            background-color: gainsboro;
            color: #0d6efd !important;
        }

            .personal-section li:hover a {
                color: #0d6efd !important;
            }

    .personal-section a {
        text-decoration: none;
        color: black;
        display: block;
        width: 100%;
    }
</style>

    <ul id="personal-section-option" class="personal-section" style="visibility:hidden">
        <li class="mb-3 p-2"><a href="/Users/UserProfile"><i class="fa-solid fa-address-card fa-xl w-15"></i> <span class="ms-2">Profile</span></a></li>
        <li><hr class=""></li>
        <li class="mb-3 p-2"><a href="/Users/Logout"><i class="fa-solid fa-right-from-bracket fa-xl w-15"></i><span class="ms-2">Logout</span></a></li>
    </ul>

<script>
    function showPersonalList() {
        var psl = document.getElementById("personal-section-option")
        console.log(psl)
        if (psl.style.visibility == 'visible') {
            psl.style.visibility = 'hidden'
        }
        else {
            psl.style.visibility = 'visible'
        }
    }


</script>

Sudoku/Views/Shared/Side_bar.cshtml
<ul class="p-0">
    <li class="side-link">@Html.ActionLink("Recently solve", "", "", new { @class = "link" }) <i class="icon fa-brands fa-dropbox"></i></li>
    <li class="side-link">@Html.ActionLink("Discussions", "", "", new { @class = "link" }) <i class="icon fa-solid fa-comments"></i></li>
    <li class="side-link">@Html.ActionLink("Favourite", "", "", new { @class = "link" })<i class="icon fa-solid fa-star"></i></li>
</ul>

Sudoku/Views/Shared/_Layout.cshtml
@{
    string isLogin = "False";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Include SweetAlert CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.css">

    <!-- Include SweetAlert JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <style>
        .side-link {
            list-style: none;
            border-radius: 12px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, .1), 0 8px 16px rgba(0, 0, 0, .1);
            padding: 10px;
            margin: 5px;
            display: flex;
            justify-content: space-between;
        }

        .link {
            text-decoration: none;
            color: darkgray;
        }

        .icon {
            line-height: inherit;
        }

        .border-radius-8 {
            border-radius: 8px;
        }

        .search {
            border-radius: 7px;
            padding: 2px 10px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Sudoku</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">
                    <li class="nav-item">
                        @Html.ActionLink("Chapter", "Index", "Chapters", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Contest", "Index", "Contests", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @RenderSection("nav_sub_item", false)
                    </li>
                    <li id="personal" onclick="showPersonalList()" class="nav-item" style="position: relative; left: 78%">
                        <button class="btn text-white border-0" type="button">
                            <i class="fa-solid fa-coins fa-xl"></i>
                            @{
                                if (Session["Point"] == null)
                                {
                                    <span class="text-white" id="point">0</span>
                                }
                                else
                                {
                                    <span class="text-white" id="point">@Session["Point"]</span>
                                }
                            }
                        </button>

                        <button class="text-white btn border-0 dropdown-toggle" role="button" aria-expanded="false">
                            @*<i class="fa-regular fa-circle-user fa-xl"></i>*@
                            <img src="@Session["UserImage"]" id="profileImage" style="width: 30px; height: 30px" alt="" loading="lazy" />
                        </button>

                        @RenderPage("~/Views/Shared/Personal_section.cshtml")
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="body-content" style="margin-top:0">
        <div class="row mb-4">
            <div class="col-lg-2 col-2 p-4 pt-5" style="border: 1px ridge">
                @*@RenderPage("~/Views/Shared/Side_bar.cshtml")*@
                @RenderSection("Left_side", false)
            </div>
            <div class="col-lg-8 col-8 pb-5 mt-4" style="background-color: whitesmoke;">
                @RenderBody()

            </div>
            <div class="col-lg-2 col-2">
                @RenderSection("Right_side", false)
            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    //$(document).ready(function () {
    //    $.ajax({
    //        url: '/users/user',
    //        type: 'get',
    //        success: function (response) {
    //            console.log(response)
    //            document.getElementById('profileImage').src = response.Profile_Image
    //        }
    //    })
    //})
</script>

Sudoku/Views/Shared/_NoneLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("scripts_nonlayout", required: false)

</body>
</html>