Sudoku/Models/Chapter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Sudoku.Models
{
    public class Chapter
    {
        public string Id { get; set; } = Guid.NewGuid().ToString().Substring(0, 7);
        public string Name { get; set; }
        public string Chap_file_path { get; set; }
        public string Type_id { get; set; }
        [ForeignKey(nameof(Type_id))]
        public ChapterType TypeNavigation { get; set; }
        public DateTime CreateDate { get; set; }
        public string AuthorId { get; set; }
        public User Author { get; set; }
    }
}

Sudoku/Models/ChapterType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sudoku.Models
{
    public class ChapterType
    {
        public ChapterType()
        {

        }
        public ChapterType(string Name, int Point)
        {
            this.Name = Name;
            this.Point = Point;
        }
        public string Id { get; set; } = Guid.NewGuid().ToString().Substring(0, 7);
        public string Name { get; set; }
        public int Point { set; get; }
    }
}

Sudoku/Controllers/ChaptersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Antlr.Runtime.Misc;
using Newtonsoft.Json.Linq;
using Sudoku.DAL;
using Sudoku.Dtos.Incoming;
using Sudoku.Dtos.Outgoing;
using Sudoku.Models;
using Sudoku.Services;

namespace Sudoku.Controllers
{
    public class ChaptersController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private SudokuService sudokuService = new SudokuService();
        private UserService userService = new UserService();
        private int ChapterQuantity {  get; set; }
        public ChaptersController()
        {
        }

        // GET: Chapters
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> Chapters(int page, string chapterName = null)
        {

            var chapterPerPage = 5;
            int skipChapter = (page - 1) * chapterPerPage;
            
            List<ChapterDto> chapters;

            var userId = userService.GetUserId(Request);

            if (chapterName == "")
            {
                ChapterQuantity = await db.Chapters.CountAsync();

                chapters = await db.Chapters.OrderBy(x => x.CreateDate)
                                      .Skip(skipChapter).Take(chapterPerPage)
                                      .Include(x => x.TypeNavigation)
                                      .Select(x => new ChapterDto
                                      {
                                          Id = x.Id,
                                          Name = x.Name,
                                          Chap_file_path = x.Chap_file_path,
                                          CreateDate = x.CreateDate,
                                          Type_id = x.Type_id,
                                          TypeNavigation = x.TypeNavigation,
                                          IsCompleted = db.Submissions.Any(s => s.ChapterId == x.Id && s.UserId == userId && s.State == utility.StateCompleted)
                                      })
                                      .ToListAsync();
            }
            else
            {
                ChapterQuantity = await db.Chapters.Where(x => x.Name.Contains(chapterName)).CountAsync();

                chapters = await db.Chapters.Where(x => x.Name.Contains(chapterName))
                                      .OrderBy(x => x.CreateDate)
                                      .Skip(skipChapter).Take(chapterPerPage)
                                      .Include(x => x.TypeNavigation)
                                      .Select(x => new ChapterDto
                                      {
                                          Id = x.Id,
                                          Name = x.Name,
                                          Chap_file_path = x.Chap_file_path,
                                          CreateDate = x.CreateDate,
                                          Type_id = x.Type_id,
                                          TypeNavigation = x.TypeNavigation,
                                          IsCompleted = db.Submissions.Any(s => s.ChapterId == x.Id && s.UserId == userId && s.State == utility.StateCompleted)
                                      })
                                      .ToListAsync();
            }

            if (ChapterQuantity == 0)
                ViewBag.PageQuantity = 0;
            else if (ChapterQuantity < chapterPerPage)
                ViewBag.PageQuantity = 1;
            else
                ViewBag.PageQuantity = Math.Ceiling((double)ChapterQuantity / chapterPerPage);

            return View(chapters);
        }
        // GET: Chapters/Create
        public async Task<ActionResult> Upsert(string id)
        {
            var chapterCreateDto = new ChapterUpsertDto();
            var items = await db.ChapterTypes.OrderByDescending(x => x.Point).Select(selector => new SelectListItem
            {
                Text = selector.Name,
                Value = selector.Id,

            }).ToListAsync();


            chapterCreateDto.ChapterType = items;
            if(id != null)
            {
                var chapter = await db.Chapters.SingleOrDefaultAsync(x => x.Id == id);
                ViewBag.SudokuArr = sudokuService.ReadSudokuStringFromFile(chapter.Chap_file_path);
                chapterCreateDto.ChapterId = chapter.Id;
                chapterCreateDto.Name = chapter.Name;
                chapterCreateDto.Type_id = chapter.Type_id;
                chapterCreateDto.Chap_file_name = chapter.Chap_file_path;
            }

            else
            {
                char[,] sudokuArr = new char[9, 9];
                for (int i = 0; i < 9; i++)
                {
                    for (int j = 0; j < 9; j++)
                    {
                        sudokuArr[i, j] = '0';
                    }
                }
                chapterCreateDto.ChapterId = "";
                ViewBag.SudokuArr = sudokuService.FormatArrayToString(sudokuArr);
            }
            string userId = userService.GetUserId(Request);
            chapterCreateDto.RemainPost = await db.AuthorService.Where(x => x.UserId == userId).Select(x => x.RemainPostNumber).SingleOrDefaultAsync(); 

            ViewBag.DefaultSudoku = sudokuService.ReadSudokuStringFromFile("default-chapter.txt");
            return View(chapterCreateDto);
        }
        [HttpPost]
        public async Task<ActionResult> Upsert(ChapterUpsertDto chapterDto)
        {
            if (ModelState.IsValid)
            {

                var userId = userService.GetUserId(Request);
                var authorService = await db.AuthorService.Where(x => x.UserId == userId).SingleOrDefaultAsync();
                if(authorService.RemainPostNumber == 0)
                {
                    return Json(new { code = 409, msg = "You have run out of posts for today" });
                }
                authorService.RemainPostNumber--;

                if(chapterDto.ChapterId == null)
                {
                    var fileName = Guid.NewGuid().ToString() + ".txt";
                    await sudokuService.WriteSudokuStringToFile(fileName, chapterDto.SudokuString);

                    var chapter = new Chapter()
                    {
                        Name = chapterDto.Name,
                        Chap_file_path = fileName,
                        Type_id = chapterDto.Type_id,
                        CreateDate = DateTime.Now,
                        AuthorId = userId
                    };
                    db.Chapters.Add(chapter);
                }
                else
                {
                    await sudokuService.WriteSudokuStringToFile(chapterDto.Chap_file_name, chapterDto.SudokuString);
                    var chapter = await db.Chapters.FindAsync(chapterDto.ChapterId);
                    chapter.Type_id = chapterDto.Type_id;
                    chapter.Name = chapterDto.Name;
                }
                await db.SaveChangesAsync();
                return Json(new { code = 200 });
            }

            chapterDto.ChapterType = await db.ChapterTypes.OrderByDescending(x => x.Point).Select(selector => new SelectListItem
            {
                Text = selector.Name,
                Value = selector.Id,
            }).ToListAsync();
            return Json(new {code = 409, msg="Lack of information"});
        }

        [HttpPost]
        public ActionResult TestConflict(string sudokuString, int rows, int columns)
        {

            var sudokuArr = sudokuService.FormatStringToArr(sudokuString, rows, columns);
            return Json(sudokuService.TestSudoku(sudokuArr)); // return code 200 if success else return box that cause conflict
        }
        [HttpGet]
        public async Task<ActionResult> GenerateRiddle(int rows)
        {
            var annealing = new SimulatedAnnealing();
            var riddle = await annealing.getRandomRiddle(rows);
            var sudokuStr = sudokuService.FormatArrayToString(riddle);
            return Json(new { code = 200, sudokuString = sudokuStr }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Play(string id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> GetChapter(string chapterId)
        {
            Chapter chapter = await db.Chapters.Where(x => x.Id == chapterId).Include(nameof(Chapter.TypeNavigation)).FirstOrDefaultAsync();

            ChapterPlayDto chapterPlayDto = new ChapterPlayDto()
            {
                chapter = chapter,
                sudokuArr = sudokuService.ReadSudokuStringFromFile(chapter.Chap_file_path)
            };
            return View(chapterPlayDto);
        }
        [HttpPost]
        public async Task<ActionResult> Play(SubmitDto submitDto)
        {
            var type = submitDto.Type_Name;
            char[,] sudokuArr;

            var userId = userService.GetUserId(Request);

            if (type == "Easy")
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 5, 5);
            else if (type == "Medium")
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 7, 7);
            else
                sudokuArr = sudokuService.FormatStringToArr(submitDto.SudokuString, 9, 9);

            string submitFileName = Guid.NewGuid().ToString().Substring(0, 6);
            string submitPath = Path.Combine(AppContext.BaseDirectory, "wwwroot", "Submission", submitFileName);

Sudoku/Controllers/RoleManageController.cs
using Stripe;
using Stripe.Checkout;
using Sudoku.DAL;
using Sudoku.Models;
using Sudoku.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Sudoku.Controllers
{
    public class RoleManageController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private UserService userService = new UserService();
        // GET: RoleManage
        public async Task<ActionResult> Index()
        {
            var packets = await db.ServicePacks.OrderBy(x => x.Fee).ToListAsync();
            return View(packets);
        }
        [HttpPost]
        public async Task<ActionResult> Checkout(ServicePack servicePack)
        {
            if (Request.Cookies["token"] == null)
                return Json(new { error = "token required" });

            string userId = userService.GetUserId(Request);
            if (userId == null)
                return Json(new { error = "invalid token" });

            StripeConfiguration.ApiKey = ConfigurationManager.AppSettings["Secretkey"];

            var url = "https://localhost:44363/RoleManage";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long)(servicePack.Fee * 100),
                            Currency = "usd",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Become author"
                            },
                        },
                        Quantity = 1,
                    },
                },
                Mode = "payment",
                SuccessUrl = url + "/ConfirmCheckout/?userId=" + userId,
                CancelUrl = url + "/Index"
            };
            var service = new SessionService();
            Session session = await service.CreateAsync(options);
            Session.Add("PacketInfo", new { id = servicePack.ID, value = servicePack.PostsPerDay });

            return Redirect(session.Url);

        }

        [HttpGet]
        public async Task<ActionResult> ConfirmCheckout()
        {
            var userId = userService.GetUserId(Request);
            if (userId == null)
                return Json(new { error = "lack of information" });

            var user = await db.Users.FindAsync(userId);
            if (user == null) 
                return Json(new { error = "user not found" });

            user.RoleId = await db.Roles.Where(x => x.Name == utility.Author).Select(x => x.Id).FirstOrDefaultAsync();

            dynamic packetInfo = Session["PacketInfo"];

            var authorService = new AuthorService();
            authorService.UserId = user.Id;
            authorService.ServiceId = packetInfo.id;
            authorService.RemainPostNumber = packetInfo.value;
            db.AuthorService.Add(authorService);

            await db.SaveChangesAsync();

            var token = userService.CreateToken(user, utility.ExpiredTimeDay);
            HttpCookie cookie = new HttpCookie("token", token);
            cookie.Secure = true;
            cookie.HttpOnly = true;
            cookie.Expires = DateTime.Now.AddDays(utility.ExpiredTimeDay);
            Response.Cookies.Set(cookie);

            return RedirectToAction("Index", "Chapters", new {page=1});
        }
    }
}

Sudoku/Views/Chapters/AuthorFeatures.cshtml
@model List<Sudoku.Models.Chapter>

@{
    ViewBag.Title = "AuthorFeatures";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your public chapters</h2>

<div class="row">
    <p class="col-4">
        @Html.ActionLink("Create New", "Upsert", new { }, new { @class = "btn btn-primary" })
    </p>
    <p class="col-6"></p>
    <p class="col-2">
        @Html.ActionLink("Change packet", "Index", "RoleManage", new { }, new { @class = "btn btn-secondary" })
    </p>
</div>
<table class="table">
    <tr>
        <th>
            Chapter name
        </th>
        <th>
            Level
        </th>
        <th>
            Point
        </th>
        <th>
            Date post
        </th>
        <th></th>
    </tr>

    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model[i].Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model[i].TypeNavigation.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model[i].TypeNavigation.Point)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model[i].CreateDate)
            </td>
            <td>
                @{
                    string editLink = "Upsert/" + Model[i].Id;
                }
                <a href="@editLink" class="btn btn-secondary me-1"><i class="fa-solid fa-pen-to-square"></i></a>
                <button type="button" onclick="onDelete(this)" data-model-id="@Model[i].Id" class="btn btn-danger me-1"><i class="fa-regular fa-trash-can"></i></button>
            </td>
        </tr>
    }

</table>
<div class="mt-4">
    <ul class="pagination justify-content-center">

        @{
            for (int i = 1; i <= ViewBag.PageQuantity; i++)
            {
                string link = "AuthorFeatures?page=" + i;
                <li class="page-item">
                    <a class="page-link" href=@link>@i</a>
                </li>
            }
        }
    </ul>
</div>
<script>
    function onDelete(obj) {
        var ele = $(obj);
        var chapterId = ele.data("model-id");
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({

                    url: '/Chapters/Delete/?id=' + chapterId,
                    type: 'post',
                    success: function (data) {
                        if (data.code == 200) {
                            location.reload();
                        }
                        else {
                            Swal.fire(
                                'Can not delete',
                                'Have been interact',
                            )
                        }
                    }
                })

            }
        })


    }
</script>

Sudoku/Views/Chapters/Chapters.cshtml
@model IEnumerable<Sudoku.Dtos.Outgoing.ChapterDto>

@{
    ViewBag.Title = "Chapters";
    Layout = "~/Views/Shared/_NoneLayoutPage.cshtml";
}

<style>

    a {
        text-decoration: none;
        color: black;
        cursor: pointer;
    }
</style>

@foreach (var item in Model)
{
    string link = "/Chapters/Play?id=" + item.Id;
    <a class="row border-chapter bg-white mb-2" href=@link>
        <div class="col-8">
            <h4>@item.Name</h4>
        </div>
        @if (item.TypeNavigation.Name == "Easy")
        {
            <div class="col-3 chapter-type text-success">
                <h4>@item.TypeNavigation.Name</h4>
            </div>
        }
        else if (item.TypeNavigation.Name == "Medium")
        {
            <div class="col-3 chapter-type text-warning">
                <h4>@item.TypeNavigation.Name</h4>
            </div>
        }
        else
        {
            <div class="col-3 chapter-type text-danger">
                <h4>@item.TypeNavigation.Name</h4>
            </div>
        }

        @if (item.IsCompleted)
        {
            <div class="col-1">
                <h4><i class="fa-solid fa-circle-check fa-xl"></i></h4>
            </div>
        }
    </a>
}
<div class="mt-4">
    <ul class="pagination justify-content-center">

        @{
            for (int i = 1; i <= ViewBag.PageQuantity; i++)
            {
                <li class="page-item">
                    <a class="page-link" onclick="getChapter(@i)">@i</a>
                </li>
            }
        }
    </ul>
</div>

<script>

</script>

Sudoku/Views/Chapters/GetChapter.cshtml
@{
    ViewBag.Title = "GetChapter";
    Layout = "~/Views/Shared/_NoneLayoutPage.cshtml";
}

@model Sudoku.Dtos.Outgoing.ChapterPlayDto

@{
    Layout = null;
}

<link href="~/Content/ChapterPlaySection/ChapterPlaySection.css" rel="stylesheet" />
<script>
        var rows = 5, columns = 5;
        var acceptRiddle = 0;
        var chapterId = document.getElementById('ChapterId').value;

        $(document).ready(function () {
            const type = document.getElementById('type').textContent;
            if (type == 'Easy') {
                rows = 5;
                columns = 5;
            }
            else if (type == 'Medium') {
                rows = 7;
                columns = 7;
            }
            else if(type == 'Hard'){
                rows = 9;
                columns = 9;
            }
        console.log(rows,columns)
            drawGrid('output',@Model.sudokuArr, rows, columns);
        });

        $('#submit').click(function () {
            var sudokuString = JSON.stringify(sudokuArr);
            var chapterType = document.getElementById('type').textContent;
            var data = {
                ChapterId: chapterId,
                SudokuString: sudokuString,
                Type_Name: chapterType
            };
            $.ajax({
                url: '/chapters/play',
                type: 'post',
                data: data,
                dataType: 'html',
                success: function (data) {
                    $('#renderPart').html(data);
                }
            })
        })
</script>


<div class="p-3">
    <div class="mb-2">
        <h2 class="col-10 mb-0">@Model.chapter.Name</h2>
    </div>
    <div class="mb-2">
        @{
            if (Model.chapter.TypeNavigation.Name == "Easy")
            {
                <span id="type" class="col-10 mb-0 text-success me-2">@Model.chapter.TypeNavigation.Name</span>
            }
            else if (Model.chapter.TypeNavigation.Name == "Medium")
            {
                <span id="type" class="col-10 mb-0 text-warning me-2">@Model.chapter.TypeNavigation.Name</span>
            }
            else
            {
                <span id="type" class="col-10 mb-0 text-danger me-2">@Model.chapter.TypeNavigation.Name</span>
            }
        }
    </div>
</div>
<div class="output" style="text-align:center">

</div>
<div class="p-3" style="text-align:end">
    <button class="btn btn-outline-dark" id="submit">Submit</button>
</div>

Sudoku/Views/Chapters/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    .border-chapter {
        border: 1px solid black;
        border-radius: 8px;
        padding: 30px 10px 30px 10px;
    }

    .chapter-type {
        justify-content: flex-end;
        display: flex;
    }

</style>

<div class="row p-4">
    <div class="col-8" id="chapterSection">

    </div>
    <div class="col-4">
        <div class="container">
            <div style=" border-radius: 8px;">
                <div class="p-3 pe-0" style="text-align: end">
                    @Html.ActionLink("Author features", "AuthorFeatures", new { }, new { @class = "btn btn-success" })
                </div>
                <hr class="mt-0" />
                <div class="p-2 mb-2">
                    <h5 style="font-weight:700">Weekly ranking</h5>
                    <div id="yourRank" class="mb-4">

                    </div>
                    <div id="WeeklyRank">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Left_side{

    <input id="chapterName" type="text" class="form-control mb-2" name="chapterName" placeholder="Name Chapter" />
    <button class="btn btn-success" type="submit" onclick="getChapter(1)">Search</button>

}

@section scripts{
    <script>
        $(document).ready(function () {
            getChapter(1)
            $.ajax({
                url: '/ranks',
                type: 'get',
                success: function (response) {
                    $('#WeeklyRank').html(response)
                }
            })

            $.ajax({
                url: '/ranks/userRank',
                type: 'get',
                success: function (response) {
                    $('#yourRank').html(response)
                }
            })

        })

        function getChapter(page) {
            var chapterName = $('#chapterName').val();
            console.log(chapterName)
            $.ajax({
                url: '/chapters/chapters/?page=' + page + '&chapterName=' + chapterName,
                type: 'get',
                typeof: 'html',
                success: function (response) {
                    $('#chapterSection').html(response)
                }
            })
        }
    </script>
}

Sudoku/Views/Chapters/Play.cshtml
@{
    ViewBag.Title = "Play";
}
<link href="~/Content/ChapterPlaySection/ChapterPlaySection.css" rel="stylesheet" />
<link href="~/Content/Grid/grid.css" rel="stylesheet" />


<div class="container">
    <div class="row p-3">
        <div class="col-9">
            <div class="container-fluid bg-white">
                <div class="subnav">
                    <div class="mb-2 mb-lg-0 d-flex justify-content-around" style="font-weight:600">
                        <button onclick="getChapter()" class="btn btn-light">Riddle</button>
                        <button class="btn btn-light" id="viewDiscussions">Discussions</button>
                        <button class="btn btn-light" id="viewSubmissions">Submissions</button>
                    </div>
                </div>
                <hr class="mt-0" />
                <div id="renderPart">



                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="container-fluid">
                <div class="p-3">

                </div>
            </div>
        </div>
    </div>
</div>
<input hidden id="ChapterId" value="@ViewBag.id" />

@section scripts{
    <script src="~/Scripts/SudokuGrid/SudokuGrid.js"></script>

    <script>

        $(document).ready(function () {
            getChapter();
        });


        $('#viewSubmissions').click(function () {
            $.ajax({
                url: '/submissions/index/?chapterId=' + chapterId,
                type: 'get',
                success: function (data) {
                    $('#renderPart').html(data);
                }
            })
        });

        $('#viewDiscussions').click(function () {
            $.ajax({
                url: '/discussions/chapterDiscussion/?chapterId=' + chapterId,
                type: 'get',
                success: function (data) {
                    $('#renderPart').html(data);
                }
            })
        });

        function getChapter() {
            var id = document.getElementById('ChapterId').value;
            $.ajax({
                url: '/Chapters/GetChapter/?chapterId=' + id,
                type: 'get',
                dataType: 'html',
                success: function (data) {
                    $('#renderPart').html(data);
                }
            })
        };
    </script>
} 